config/routes.rb
MingleEstimation::Application.routes.draw do
  resources :sessions

  resources :projects do
    get 'list_cards',:on => :collection
    get 'pull_cards',:on => :collection
    get 'show_card', :on => :collection
    get 'send_email',:on => :collection
    get 'show_all_cards', :on=> :collection
    get 'show_user_estimation', :on=> :collection
    delete 'destroy_card',:on => :collection
  end
  resources :sessions

  match '/projects/set_project_name', :to=> 'projects#set_project_name'

   root :to => 'projects#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :estimate,:comments
  belongs_to :user
  belongs_to :card
  belongs_to :project

  validates_uniqueness_of :number, :scope => :project_id

  has_many :estimation_details
end

app/models/estimation_detail.rb
class EstimationDetail < ActiveRecord::Base
  attr_accessible :estimate, :comments
  belongs_to :card
  belongs_to :user

  validates_presence_of :estimate
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :cards, dependent: :destroy
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessor :email, :password, :match
  attr_accessible :email, :password

  belongs_to :user

  before_validation :authenticate_user

  validates_presence_of :match,
                        :message => 'for your name and password could not be found',
                        :unless => :session_has_been_associated?

  before_save :associate_session_to_user

  private

  def authenticate_user
    if not session_has_been_associated? and valid_credentials?
      user = User.where(
          email_id: self.email,
          password: self.password
      ).first_or_create
      self.match = user
    else
      self.match = nil
    end
  end

  def valid_credentials?
    mingle_user.valid_credentials?
  end

  def mingle_user
    Mingle4r::MingleClient.new('https://careerbuilder.mingle.thoughtworks.com/',
                               self.email, self.password)
  end

  def associate_session_to_user
    self.match = User.where(
        email_id: self.email
    ).last
    self.user_id ||= self.match.try(:id)
  end

  def session_has_been_associated?
    associate_session_to_user
    not self.user_id.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :is_admin, :password
  has_many :estimation_details
  has_many :cards
  has_many :sessions, dependent: :destroy
  # before_save :encrypt_password



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :maintain_session_and_user

  def ensure_login
    unless @user
      flash[:notice] = "Please login to continue"
      redirect_to(new_session_path)
    end
  end

  def ensure_logout
    if @user
      flash[:notice] = "You must logout before you can login or register"
      redirect_to(root_url)
    end
  end

  private

  def maintain_session_and_user
    if session[:id]
      if @application_session = Session.find_by_id(session[:id])
        @user = @application_session.user 
        @user.reload
        @user       
      else
        session[:id] = nil
        redirect_to(root_url)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ActionView::Helpers::TextHelper
  before_filter :ensure_login

  def index
  	@projects = LetsMingle.new(@user.email_id,@user.password).get_projects
  end

  def set_project_name
    @project = Project.where(:mingle_name => params["project"]["name"]).first_or_create    
    @db_cards = @project.cards.where("estimation is null")
    LetsMingle.new(@user.email_id, @user.password, params["project"]["name"] ).update_user
    render 'list_cards'
  end

  def pull_cards
 	@cards = LetsMingle.new(@user.email_id, @user.password, params["project_name"] ).get_cards
    project = Project.where(:mingle_name => params["project_name"]).first_or_create 
    unless @cards.blank?
      @cards.each do|a|
        card = Card.new
        card.number = a[:number]
        card.url = a[:name]
        card.description = a[:description]
        card.card_type = a[:type]
        card.mingle_id = a[:id]
        card.user_id = @user.id
        card.project_id = project.id
        card.save
      end
    @db_cards = project.cards.where("estimation is null")
    end
    respond_to(:js) 
  end

  def list_cards
    show_all_cards
  end

  def send_email
    comment = params[:email_notify]["comment"]
    url     = params[:email_notify]["url"]
    MingleMailer.welcome_email(@user,comment,url,params["email_notify"]["project_name"])
    flash[:notice] = "Email Notification Sent"
    redirect_to root_path
  end

  def show_card
    @show_card = Card.find(params[:id])
  end

  def show_user_estimation
  	project = Project.where(:mingle_name => params["project_name"]).first_or_create
  	cards = project.cards.where("estimation is null")
  	@est = EstimationDetail.where(:card_id=>cards.pluck(:id))
  	@uniq_card = @est.pluck(:card_id).uniq
  	respond_to(:js)
  end

  def update
    @card = Card.find(params[:id])
    estimation_detail = EstimationDetail.find_by_card_id_and_user_id(@card.id,@user.id)
    if @user.is_admin
    m_c = LetsMingle.new(@user.email_id, @user.password, @card.project.mingle_name ).project_login
    story_card =  m_c.project.find_card(@card.number) 
    story_card.property_value('Estimate', params[:card][:estimate])
    story_card.save
    end
    unless estimation_detail.blank?
      if estimation_detail.update_attributes(:estimate => params[:card][:estimate],:comments => params[:comments])
        @card.update_attributes(:estimate => params[:card][:estimate]) if @user.is_admin
        flash[:notice] = "Estimation updated Successfully"
        redirect_to list_cards_projects_path(:id=>params[:id],:project=>{:name => @card.project.mingle_name})
      else
        flash[:notice] = "Some Problem is there. Please review the details"
        redirect_to show_card_projects_path
      end
    else
      estimation_detail          = EstimationDetail.new
      estimation_detail.user_id  = @user.id
      estimation_detail.estimate = params[:card][:estimate]
      estimation_detail.card_id  = @card.id
      estimation_detail.number   = @card.number
      estimation_detail.comments = params[:comments]
      estimation_detail.save
      if estimation_detail.save
        @card.update_attributes(:estimate => params[:card][:estimate]) if @user.is_admin
        flash[:notice] = "Estimation updated Successfully"
        redirect_to list_cards_projects_path(:id=>params[:id],:project=>{:name => @card.project.mingle_name})
      else
        flash[:notice] = "Some Problem is there. Please review the details"
        redirect_to show_card_projects_path
      end
    end

  end

  def show
     @cards = EstimationDetail.where(params[:number])
    #raise @cards.inspect
  end
  
  def destroy_card
    @card = Card.find(params[:id])
    @card.destroy
    respond_to(:js) 
  end

  def show_all_cards
     card = Card.find(params[:id])
     @project = card.project
    @db_cards = @project.cards.where("estimation is null")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :ensure_login, :only => :destroy
  #before_filter :ensure_logout, :only => [:new, :create]

  def index
    redirect_to(new_session_path)
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(params[:session])
    if @session.save
      session[:id] = @session.id
      flash[:notice] = "Hello #{@session.user.email_id}, you are now logged in"
      redirect_to(root_url)
    else
      render(:action => 'new')
    end
  end

  def destroy
    Session.destroy(@application_session)
    session[:id] = @user = nil
    flash[:notice] = "You are now logged out"
    redirect_to(root_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
      when :notice then "alert fade in alert-info"
      when :success then "alert fade in alert-success"
      when :error then "alert fade in alert-error"
      when :alert then "alert fade in alert-error"
    end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lets Mingle" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top" >
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Lets - Mingle</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
             <% if @user %>
               <li><%= link_to "Logout", @application_session, :method => :delete %></li>
             <% else %>
               <li><%= link_to "Login", new_session_path %></li>
             <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <!--<div class="well sidebar-nav">-->
            <!--<ul class="nav nav-list">-->
              <!--<li class="nav-header">Sidebar</li>-->
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
        </div><!--/span-->
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Lets Mingle 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_merge_cards.html.erb
<div id="remove_cards">
<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th>Card Number</th>
      <th>Name</th>
      <th>Description</th>
    </tr>
    </thead>

    <tbody>
    <%@db_cards.each do |card| %>
        <tr class="card_<%=card.id%>">
          <td><%= link_to card.number,show_card_projects_path(:id=>card.id), :class => "btn btn-primary" %></td>
          <td><%= truncate(card.url,:length=>25) %></td>
          <td><%= truncate(Sanitize.clean(card.description), :length=>50)  %></td>
          <td><%= link_to 'Delete', destroy_card_projects_path(:id=>card.id), { class: 'btn btn-danger', remote: true, method: :delete , :data => { :confirm => 'Are you sure?' }}%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/projects/_user_estimation_cards.html.erb
<h3><%= "Listing All Users Estimations" %></h3>
<div id = "remove_estimation_cards">
<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th>Card Number</th>
      <%@est.pluck(:user_id).uniq.each do |e|%>
      <th><%=User.find(e).email_id.gsub("@careerbuilder.com","")%></th>
      <%end%>
    </tr>
    </thead>

    <tbody>
    <%@uniq_card.each do |card_id| %>
    <%card = Card.find(card_id)%>
        <tr>
          <td><%= link_to card.number,show_card_projects_path(:id=>card.id), :class => "btn btn-primary" %></td>
              <%@est.pluck(:user_id).uniq.each do |es|%>
              <% e= EstimationDetail.find_by_card_id_and_user_id(card.id, es)%>
                <%unless e.blank? %>
                  <td>
                    <%card_id = e.id%>      
                    <a id="popoverOption_<%=card_id%>" class="btn btn-success" data-content="<%=e.comments %>" rel="popover" data-placement="bottom"><%= e.estimate%></a>
                    </td>
                    <script>
                      $('#popoverOption_<%=e.id%>').popover({ trigger: "hover" });
                    </script>
                <%else%>
                  <td></td>
                <%end%>         
              <%end%>          
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/projects/destroy_card.js.erb
$(".card_<%= params[:id]%>").css({"background-color":"#B40404"})
$(".card_<%= params[:id]%>").fadeOut(2000);

app/views/projects/index.html.erb
<div class="span3"></div>
<div class="span6">
  <fieldset style="width:75%;">
<h1>Projects</h1></br>
<%= simple_form_for Project.new, :url =>projects_set_project_name_path,:method => 'post' do |f| %>
  <%=f.input :name, collection: @projects, as: :radio_buttons,
    input_html: { onclick:"document.getElementById('new_project').submit();" }, :label=> false %>  
<%end%>
</fieldset>
</div>

app/views/projects/list_cards.html.erb
<%if @user.reload && @user.is_admin %>
  <%@db_cards = @project.cards.where("estimation is null") %>
  <%=button_tag "Pull Cards", id: "pull_cards", :class => "btn btn-primary" %>
  <%= image_tag("ajax-loader.gif", :style=>"display:none;", :id => "loader")%>
  <%=button_tag "List User Estimated Cards", id: "user_estimate_cards", :class => "btn btn-info" %>
  <%= image_tag("ajax-loader.gif", :style=>"display:none;", :id => "loader")%>
  <%= render :partial => "merge_cards" unless @db_cards.blank? %>
<div id = "past_cards"></div>
<div id= "show_estimated_cards"></div>
<%else%>
  <%= render :partial => "merge_cards" %>
<%end%>


<% if @user.reload && @user.is_admin %>
<%= simple_form_for "email_notify", :url=> 'send_email',:method => :get do |f| %>
  <%= f.input :comment, as: :text , input_html: {style: 'height:100px; width:300px;'}  %>
  <%= f.input :project_name, :as => :hidden, :input_html => { :value =>  params[:project][:name]} %>
  <%= f.input :url, :as => :hidden, :input_html => { :value =>  "http://23.21.128.221:3000/projects"} %>
   <%= f.button :submit , 'Send Email Notification' %>
<% end %>
<% end %>

<script>
    $('#pull_cards').click(function() {
        $("#loader").show();
        $('#remove_cards').hide();
        $.ajax({
            url: "/projects/pull_cards",
            data: {project_name :'<%=params[:project][:name] if params[:project]%>'}
        });
    });

    $('#user_estimate_cards').click(function() {
      $("#loader").show();
      $('#remove_estimation_cards').hide();

        $.ajax({
            url: "/projects/show_user_estimation",
            data: {project_name :'<%=params[:project][:name] if params[:project]%>'}
        });
    });
</script>

app/views/projects/pull_cards.js.erb
$("#past_cards").empty();
$("#past_cards").append('<%=j render :partial => "merge_cards"%>');
$("#loader").hide();

app/views/projects/show.html.erb
<%#raise @cards.inspect%>

app/views/projects/show_all_cards.html.erb
<%= render :partial => "merge_cards" %>

app/views/projects/show_card.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Baraja: A Plugin for Spreading Items in a Card-Like Fashion" />
  <meta name="keywords" content="jquery, plugin, transform, css3, cards, spread, items, web development" />
  <link rel="stylesheet" type="text/css" href="/assets/baraja.css" />
  <link rel="stylesheet" type="text/css" href="/assets/demo.css" />
  <link rel="stylesheet" type="text/css" href="/assets/custom.css" />
  <script type="text/javascript" src="/assets/modernizr.custom.79639.js"></script>
</head>
<body>
<div class="table-responsive">
  <div>
  <%= simple_form_for(@show_card,:url => project_path(:id => @show_card.id)) do |f| %>
      <p> 
        <div class="page-header" style="border-bottom: 1px solid rgb(238, 238, 238);">
           <h3 style="color: rgb(51, 51, 51);"> <%= "#"+@show_card.number.to_s+" - " +@show_card.url %></h3>
        </div>       
      </p>    
      <p>    
        <%= raw @show_card.description.gsub("<p>&nbsp;</p>\n\n<p>&nbsp;</p>\n\n","").gsub("<h2>","<h4>") %>
      </p>
        </div>

      <div>
        <p>
          <b>Estimation:</b>
          <%= f.text_field 'estimate' ,:value=>EstimationDetail.find_by_card_id_and_user_id(@show_card.id,@user.id).try(:estimate),:required => true%>
        </p>      
     </div>


<!--<div class="container">-->

  <!--<section class="main">-->

    <div class="baraja-demo" >
      <p>
        <b>Select Your Estimation:</b>
      </p>
      <ul id="baraja-el" class="baraja-container">
        <li id="1"><%= image_tag("11.jpg")%></li>
        <li id="2"><%= image_tag("22.jpg")%></li>
        <li id="3"><%= image_tag("33.jpg")%></li>
        <li id="5"><%= image_tag("55.jpg")%></li>
        <li id="8"><%= image_tag("88.jpg")%></li>
      </ul>
    </div>
  <!--</section>-->

<!--</div>-->

          <p>
            <b>Judge your Estimation:</b>
            <%= text_area :comments, "",:value=>EstimationDetail.find_by_card_id_and_user_id(@show_card.id,@user.id).try(:comments),:cols => "15",:rows=>"4" %>
          </p>
        </div>

      <p>
        <%= f.submit :class=>"btn btn-danger" %>
      </p>
  <% end %>


<%= link_to "Back",list_cards_projects_path(:id => @show_card.id, :project => {:name => @show_card.project.mingle_name}),:class => "btn btn-primary" %>

    </div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="/assets/jquery.baraja.js"></script>
<script type="text/javascript">
    $(function() {

        var $el = $( '#baraja-el' ),
                baraja = $el.baraja();


    });
</script>
</body>
</html>

app/views/projects/show_user_estimation.js.erb
$("#show_estimated_cards").empty();
$("#show_estimated_cards").append('<%=j render :partial => "user_estimation_cards"%>')
$("#loader").hide();